# Generated by Django 3.2.13 on 2022-06-03 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='points',
            new_name='pointcount',
        ),
    ]
