# Generated by Django 3.2.13 on 2022-07-18 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_discount_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='percentile',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
