# Generated by Django 3.2.13 on 2022-05-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_to',
            field=models.CharField(choices=[('OP', 'Problem with order'), ('DP', 'Problem with delivery'), ('SQ', 'Some question'), ('SM', 'Some problem')], default='SQ', max_length=2),
        ),
    ]
