# Generated by Django 3.2.13 on 2022-06-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0004_auto_20220601_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_email',
        ),
    ]
