# Generated by Django 3.2.13 on 2022-05-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_company', models.CharField(choices=[('NP', 'New Post'), ('UkrP', 'Ukr Post'), ('MT', 'Meest'), ('JN', 'Justin')], default='', max_length=10)),
                ('delivery_office_number', models.IntegerField(default='')),
                ('addressee_first_name', models.CharField(max_length=32)),
                ('addressee_last_name', models.CharField(max_length=32)),
                ('addressee_phone', models.CharField(max_length=10)),
                ('delivery', models.CharField(choices=[('PickUp', 'Pick-up from our stores'), ('PickUpDelivDepartment', 'Pick-up from delivery department'), ('Courier', 'Courier')], default='', max_length=32)),
                ('status', models.CharField(choices=[('AwaitingShipment', 'Awaiting Shipment'), ('InDelivery', 'In Delivery Service'), ('OnTheWay', 'On the way'), ('OnDepartment', 'Order on delivery department'), ('Received', 'Received')], default='AwaitingShipment', max_length=32)),
                ('comment', models.CharField(max_length=200)),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
