# Generated by Django 3.2.13 on 2022-05-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='descrption',
            field=models.TextField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='upload',
            field=models.ImageField(default='uploads/no_image.png', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
