# Generated by Django 3.2.13 on 2022-05-24 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_question_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
