# Generated by Django 3.2.13 on 2022-05-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date action'),
        ),
    ]
