# Generated by Django 3.2.13 on 2022-05-06 16:40

import apps.payments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsystemlog',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='paymentsystemlog',
            name='response',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_system',
            field=models.CharField(choices=[('PayPal', 'PayPal'), ('Liqpay', 'Liqpay'), ('Portmone', 'Portmone')], default='PayPal', max_length=30),
        ),
        migrations.AddField(
            model_name='paymentsystemlog',
            name='payment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentsystemlog',
            name='request_data',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='paymentsystemlog',
            name='response_data',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='payment',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[apps.payments.models.Payment.validate_price]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='products_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[apps.payments.models.Payment.validate_price]),
        ),
    ]
