# Generated by Django 3.2.13 on 2022-05-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_delivery_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_system',
            new_name='system',
        ),
    ]
