# Generated by Django 3.2.13 on 2022-05-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20220524_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Processing', 'Processing'), ('Canceled', 'Canceled')], default='Processing', max_length=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_system',
            field=models.CharField(choices=[('PayPal', 'PayPal'), ('Liqpay', 'Liqpay'), ('Portmone', 'Portmone')], default='PayPal', max_length=30),
        ),
    ]
