# Generated by Django 3.2.13 on 2022-05-27 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0007_payment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
