# Generated by Django 3.2 on 2022-05-20 13:45

import apps.orders.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_line2',
        ),
        migrations.AddField(
            model_name='order',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[apps.orders.models.Order.validate_order_value]),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address_line',
            field=models.CharField(default=False, max_length=1024, verbose_name='Address line'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='orders.shippingaddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(default=False, max_length=56, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default=False, max_length=56, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(default=False, max_length=512, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='post_code',
            field=models.CharField(default=False, max_length=8, verbose_name='Postcode'),
        ),
    ]
