# Generated by Django 3.2 on 2022-05-20 15:07

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220520_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[apps.orders.models.Order.validate_order_value]),
        ),
    ]
