# Generated by Django 3.2.13 on 2022-05-31 17:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('shipments', '0001_initial'),
        ('orders', '0004_auto_20220525_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Delivery_Address', to='shipments.shipments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
