# Generated by Django 3.2 on 2022-06-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20220531_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address',
            new_name='shipment',
        ),
    ]
