# Generated by Django 3.2 on 2022-06-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_delivery_address_order_shipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='date_created',
        ),
    ]
