# Generated by Django 3.2 on 2022-06-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
