# Generated by Django 3.2.7 on 2022-04-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
