# Generated by Django 3.2.13 on 2022-04-30 16:49

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=10)),
                ('preferable_language', models.CharField(choices=[('UA', 'Украинский'), ('EN', 'English')], default='EN', max_length=2)),
                ('addresses_of_delivery', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=150), size=None)),
                ('telephones', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=16), default=list, size=None)),
                ('additional_emails', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=150), default=list, size=None)),
            ],
        ),
    ]
