# Generated by Django 3.2.13 on 2022-04-30 17:02

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_auto_20220430_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='additional_emails',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.EmailField(max_length=150), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='addresses_of_delivery',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='telephones',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, null=True, size=None),
        ),
    ]
