# Generated by Django 3.2.13 on 2022-05-10 19:58

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('userprofiles', '0004_alter_userprofiles_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to='auth.user')),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('preferable_language', models.CharField(choices=[('UA', 'Украинский'), ('EN', 'English')], default='EN', max_length=2)),
                ('addresses_of_delivery', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, null=True, size=None)),
                ('telephones', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, null=True, size=None)),
                ('additional_emails', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.EmailField(max_length=150), blank=True, null=True, size=None)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.DeleteModel(
            name='UserProfiles',
        ),
    ]
